### ISSUE TITLE
Проблема в работе ПО БКО на ОС Windows 10 LTSC x64 RUS

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#22]
При работе с программой БКО v1.7.6.1 в ОС Windows 10 у меня при выделении любого объекта (компьютер, монитор, принтер и .т.д) выходит вот какая ошибка 2 раза подряд: [Ссылка на скрин с ошибкой](https://fastpic.ru/view/114/2020/1018/_4a78c0f05efff58989e50c29fe8206e3.jpg.html)
"В GDI+ возникла ошибка общего вида"

Скорее всего такая ошибка выходит при прорисовке QR кода в программе!

**Comment by bdi1979** [comment]
При чём на ОС Windows 7 x64 RUS никаких ошибок не было с этой версией программы!

**Comment by bdi1979** [comment]
> При работе с программой БКО v1.7.6.1 в ОС Windows 10 у меня при выделении любого объекта (компьютер, монитор, принтер и .т.д) выходит вот какая ошибка 2 раза подряд: [https://fastpic.ru/view/114/2020/1018/_4a78c0f05efff58989e50c29fe8206e3.jpg.html](url)
> 
> Скорее всего такая ошибка выходит при прорисовке QR кода в программе!

Может в системе Wiondows 10 не хватает каких нибудь компонентов?

**Comment by ldragon24** [comment]
Приветствую.
попробуйте вот это обновление -
https://drive.google.com/file/d/1F0nO7Vh18TD_9vNbYe3ibUYbRb3f4nKZ/view?usp=sharing

вс, 18 окт. 2020 г. в 12:42, DENIS <notifications@github.com>:
