### ISSUE TITLE
Ошибка в ПО БКО v1.7.6.1 при добавлении любого принтера вручную

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#23]
При ручном вводе принтера в программе у меня выходит вот какая ошибка: [Ссылка на скрин с ошибкой](https://fastpic.ru/view/114/2020/1018/_423e24519e519d00a42ec49df32ef7bb.jpg.html)
"Ошибка синтаксиса в инструкции UPDATE"
возможно такая ошибка проявляется не только при вводе принтера!?

**Comment by ldragon24** [comment]
Попробуйте вот это обновление:
https://drive.google.com/file/d/1F0nO7Vh18TD_9vNbYe3ibUYbRb3f4nKZ/view?usp=sharing
