### ISSUE TITLE
Попробуйте вот это обновление:

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#24]
Попробуйте вот это обновление:
https://drive.google.com/file/d/1F0nO7Vh18TD_9vNbYe3ibUYbRb3f4nKZ/view?usp=sharing

_Originally posted by @ldragon24 in https://github.com/ldragon24/bko/issue_comments/711761742_

**Comment by bdi1979** [comment]
Ошибка "**В GDI+ возникла ошибка общего вида**" стала теперь выпадать только один раз при выборе любого объекта.
А ошибка "**Ошибка синтаксиса в инструкции UPDATE**" при добавлении любого принтера исчезла! Спасибо огромное за исправление!

И ещё небольшая просьба. Не закрывайте пожалуйста "**Инциденты**", чтобы не открывать новые для ответа!

**Comment by ldragon24** [comment]
в программе в меню есть - письмо авторам, можно воспользоваться для связи...

**Comment by ldragon24** [comment]
С ошибкой GDI - не могу воспроизвести, пока увы...

**Comment by bdi1979** [comment]
Я могу вечером после работы дать доступ Тимвьювером для проверки

вт, 20 окт. 2020 г., 13:26 Alex Plotnikov <notifications@github.com>:
