### ISSUE TITLE
Как обновить 1.7.5.2 до 1.7.6.3

### ISSUE THREAD

**Issue by Kladkevich** [ldragon24/bko#25]
Здравствуйте как можно обновить ms sql базу с 1.7.5.2 до 1.7.6.3? Без потери данных? Уже используем много лет потеря данных важна для нас. Спасибо

**Comment by ldragon24** [comment]
Для начала сделайте бэкап своей базы, может всякое случиться.
Затем запустите новую версию, программа скажет вам что база отличается от эталонной и внесет изменения в структуру базы данных. Если все пройдет удачно программа запустится, если нет то увы, придется руками...

**Comment by Kladkevich** [comment]
Да все сработало. При запуске на любом устройстве ошибка "В GDI+ возникла ошибка общего вида". С чем это связано? Вносить изменения дает, Добавлять тоже

**Comment by ldragon24** [comment]
весь текст ошибки бы увидеть, у меня эта ошибка не воспроизводится.
