### ISSUE TITLE
Ошибка в ПО БКО v1.7.6.3

### ISSUE THREAD

**Issue by Kladkevich** [ldragon24/bko#26]
Windows server 2016, MS SQL 2017
И при отрытии любой техники такое сообщение.
![БКО](https://user-images.githubusercontent.com/73980682/98496687-674f6180-226c-11eb-9e80-0c62981d11b8.jpg)

**Comment by ldragon24** [comment]
Попробуйте вот это обновление - https://drive.google.com/file/d/1CON04MHvh9joD_qixz9KcRjmr-BtBlF4/view?usp=sharing
В настройках отключите возможность формирования QR кода. Возможно поможет, я воспроизвести данную ошибку не могу, не на одной версии винды у меня она не возникает.

**Comment by Kladkevich** [comment]
После обновления ошибка ушла. В настройках ничего не трогал. Спасибо
