### ISSUE TITLE
БКО версия 1.7.6.4 ошибки

### ISSUE THREAD

**Issue by Kladkevich** [ldragon24/bko#27]
У нас MS SQL на сервере на локальной машине установлена программа. Версия программы после предыдущих обращений к вам БКО версия 1.7.6.4 На локальной машине при выборе ПК и сформировать отчет программа вешается. До обновления все работало. На сервере запускаю в программе БКО "Проверить структуру" ошибка. Что можно сделать 
![БКОerror](https://user-images.githubusercontent.com/73980682/100837080-b7e86200-349a-11eb-8dab-409195466d20.jpg)

**Comment by ldragon24** [comment]
1. Какой отчет?
2. Офисный пакет?
3. Версия ОС?
4. Версия СУБД?

**Comment by Kladkevich** [comment]
Любой вообще отчет. 
Офис 2016 Про x64
Win 10Pro x64 Версия 20h2
Microsoft SQL Server Management Studio	14.0.17254.0
Сервер 2012 r2
На клинских машинах стало вылетать сообщение
![Безымянный](https://user-images.githubusercontent.com/73980682/100843665-e79c6780-34a4-11eb-9c1d-5fd3689b00a4.jpg)

**Comment by ldragon24** [comment]
1. В настрйоках программы офисный пакет выбран какой?
2. Соединение с сервером как организовано (MS SQL 2008, MS SQL, DSN)?

**Comment by Kladkevich** [comment]
Проблема с отчетам решилась не углядел.
Соединение MS SQL

**Comment by Kladkevich** [comment]
При раскрытии дерева возникает сообшение на клиентах.
В отчете Паспорт компьютера нет программного правильно?

**Comment by ldragon24** [comment]
Замените соединение на ms sql 2008

**Comment by Kladkevich** [comment]
На сервере не дает поменять. Если на клиенте меняем тогда тоже самое сообщение.

**Comment by ldragon24** [comment]
т.е. при выборе объекта в дереве техники вы получаете сообщение о наличии строки нулевой длинны в базе? 
Скачайте вот это - https://drive.google.com/file/d/1CON04MHvh9joD_qixz9KcRjmr-BtBlF4/view?usp=sharing
В меню сервис\обслуживание бд\удаление строк нулевой длинны.

**Comment by Kladkevich** [comment]
не помогло. Ошибка так и осталась. Может базу выслать?

**Comment by ldragon24** [comment]
как вариант

**Comment by Kladkevich** [comment]
[movedb_backup_2020_12_03_000921_6898690.zip](https://github.com/ldragon24/bko/files/5634436/movedb_backup_2020_12_03_000921_6898690.zip)

**Comment by ldragon24** [comment]
при выборе какой техники выходит сообщение?

**Comment by ldragon24** [comment]
Воспроизвел проблему.
Качаем - https://drive.google.com/file/d/1CON04MHvh9joD_qixz9KcRjmr-BtBlF4/view?usp=sharing
Выполняем:
В меню сервис\обслуживание бд\удаление строк нулевой длинны.

**Comment by Kladkevich** [comment]
Ошибка пропала. Но при добавлении нового ПК сохранении его. Выводим паспорт этого компьютера и  открываться много отчетов до без конечности. И пока не завершить службу программы и печати открывает

**Comment by ldragon24** [comment]
Библиотеки которые идут в архиев с обновление тоже обновили?

**Comment by Kladkevich** [comment]
Главный корпус\ учебно воспитанельная служба \ библиотека \MOBILE-BIBL На этом ПК ситуация повторилась. На старой технике

**Comment by ldragon24** [comment]
Откройте базу, выполните запрос - UPDATE [movedb].[dbo].[kompy] SET nplomb ='' WHERE nplomb IS NULL;

**Comment by Kladkevich** [comment]
затронуто 0 строк

**Comment by ldragon24** [comment]
SELECT *
  FROM [movedb].[dbo].[kompy];

Посмотрите визуально есть где графы с null

**Comment by Kladkevich** [comment]
обновил на клиенте тоже самое. Нормально стал на MOBILE-BIBL
Добавил новую машину через *.ini далее делаю соранение и паспорт и все циклическое открытие. Старые нормально отрывает проверил не все правда.

**Comment by Kladkevich** [comment]
графы с null пустые то есть? 
Если да то есть и много

**Comment by ldragon24** [comment]
нет, там будет написано NULL

**Comment by Kladkevich** [comment]
А как можно главное чтоб можно было по сети с базой? может удален ку дать?

**Comment by Kladkevich** [comment]
просто с программой работают 5 человек. на разных местах

**Comment by Kladkevich** [comment]
![1234](https://user-images.githubusercontent.com/73980682/100999440-fe1aef80-3586-11eb-90ad-e37eeb8c52f8.jpg)
И таких записей много

**Comment by ldragon24** [comment]
можно аксесную базу на сетевую шару положить и настроить путь к ней на клиентах

**Comment by Kladkevich** [comment]
были на ней. перешли только не помню почему

**Comment by ldragon24** [comment]
> И таких записей много

пустая графа это ерунда, а вот графы с содержимым NULL почему то у вас выдают ошибку. Возможно сервер настроен как то по хитрому...

**Comment by Kladkevich** [comment]
И как нам быть? да если переключаем на ms sql 2008 выдает 
![11111111](https://user-images.githubusercontent.com/73980682/101129083-252afd00-362b-11eb-8da2-e6f34352d16a.jpg)

**Comment by Kladkevich** [comment]
Прописываю ODBC если не помогает.

**Comment by ldragon24** [comment]
для скул до 2008 использовался драйвер один, после 2008 стал использоваться нативный драйвер. если версия скул больше или равно 2008 то выбирайте соединение мкул 2008. дело не в подключении а в настройках самого сервера. Выдаваемая ошибка - что то делаете не так, я не могу точно определить проблему по столь малому описанию, что вводите, как вводите, указываете ли порт, имя пользователя, пароль, адрес сервера и все такое...
Если не затруднит пишите лучше на почту или в ватсап. думаю так будет быстрее....

**Comment by Kladkevich** [comment]
Все решил пока проблемы с удалением пустых строк вот так DELETE From [movedb].[dbo].[kompy]
Where (CPU1 is null or CPU1 = '')

**Comment by ldragon24** [comment]
> Все решил пока проблемы с удалением пустых строк вот так DELETE From [movedb].[dbo].[kompy]
> Where (CPU1 is null or CPU1 = '')

UPDATE [movedb].[dbo].[kompy] SET CPU1 ='' WHERE CPU1 IS NULL;

не пустых а нулевых, это разные вещи. к тому же в программе это все делается, я Вам говорил как.

**Comment by Kladkevich** [comment]
Re: [ldragon24/bko] БКО версия 1.7.6.4 ошибки (#27)


Здравствуйте, Alex.

Вы писали 7 декабря 2020 г., 12:58:01:





Все решил пока проблемы с удалением пустых строк вот так DELETE From [movedb].[dbo].[kompy]
Where (CPU1 is null or CPU1 = '')
UPDATE [movedb].[dbo].[kompy] SET CPU1 ='' WHERE CPU1 IS NULL;
не пустых а нулевых, это разные вещи. к тому же в программе это все делается, я Вам говорил как.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



Все же проблема осталась какая то. Вносим новый ПК через ini файл. При выводе паспорта компьютера идет циклическое отрывание одного паспорта.(Больше 100 открыл) Помогает выгрузить программу из служб и перезапуск службы печати. И при добавлении нового ПК номер в базе стал писаться номер в базе 1554 хотя техники 397 

-- 
С уважением,
 Кладкевич                          mailto:Kladkevich_82@mail.ru

**Comment by ldragon24** [comment]
1. Номер в базе - это индекс таблицы СУБД.
2.  попробуйте скачать вот это - https://drive.google.com/file/d/1CON04MHvh9joD_qixz9KcRjmr-BtBlF4/view?usp=sharing
