### ISSUE TITLE
БКО 1.7.6.4 MySQL Connector ODBC 3.51 vs Connector ODBC 5.1 

### ISSUE THREAD

**Issue by bitewolf** [ldragon24/bko#29]
Понимаю, что тут проблема скорее с ODBC драйвером, но может Вы подскажите как можно это решить.

При использовании Connector ODBC 3.51 - вместо русских букв знаки вопроса. (пробовал 3.51.28, 3.51.29, 3.51.30)
![Screenshot_2](https://user-images.githubusercontent.com/6371699/116453093-1e658680-a867-11eb-9c40-418df8d5fd08.png)

При использовании Connector ODBC 5.1 - не могу добавить новую запись, выдает ошибку - Драйвер ODBC не поддерживает требуемые свойства (удаление, просмотр, редактирование с последующим сохранением работает)
![Screenshot_1](https://user-images.githubusercontent.com/6371699/116453060-13aaf180-a867-11eb-87b9-2546b99e369b.png)

Тестировал на Windows 7 x64 SP1 и Windows 10 x64 20H2
MySQL сервер запущен через XAMPP x64 8.0.3

Базу конвертировал из .mdb в .sql дамп с помощью msa2mys, а потом заменял VARCHAR(255) VARCHAR(100) VARCHAR(50) на LONGTEXT. После чего импортировал на сервер.

**Comment by ldragon24** [comment]
С 3,51 проблема в кодировке установленной для конкретной базы. Попробуйте поменять.

**Comment by bitewolf** [comment]
Спасибо! Изменил в файле  c:\xampp\mysql\bin\my.ini все что связано с кодировкой на кириллицу:
```
[client]
default-character-set=cp1251

[mysqld]
init-connect=\'SET NAMES cp1251\'
collation_server=cp1251_general_ci
character_set_server=cp1251
skip-character-set-client-handshake
```
Теперь все отлично работает на Connector ODBC 3.51 и на Connector ODBC 5.1

P.S. может кому-то будет полезно:
БКО показывает русские буквы не зависимо от настроек "сравнение" в БД, у меня по крайней мере.
![33](https://user-images.githubusercontent.com/6371699/116784059-bd25f900-aa9a-11eb-901c-5d9050f78eb4.png)
