### ISSUE TITLE
Новые возможности программы БКО

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#30]
Я думаю что данный вопрос будет актуален многим системным администраторам в работе с программой БКО!
Суть вопроса вот в чём:
Как правило, админы в своей работе обслуживают не одну контору, а несколько. Соответственно одновременно ему необходимо пользоваться не одной базой в программе БКО. Программа позволяет использовать несколько разных баз, но проблема как раз вот в чём:
1. Было бы очень удобно если бы базы можно было бы разложить по отдельным папкам, т.к. многие используют синхронизацию с сервером конторы и все конторы разные. (А большинство программ синхронизации работают только с папками). Соответственно не хотелось бы, чтобы на сервер конторы синхронизировались все базы БКО которые есть у админа.

**Comment by bdi1979** [comment]
Между рабочими компами админа синхронизировать базы можно и все разом, но бывают случаи когда ты работаешь с разными конторами и с разными помогайками в этих конторах. Которым не надо давать доступ с другим базам программы БКО.

**Comment by bdi1979** [comment]
Вот как быть в данном случае?

**Comment by ldragon24** [comment]
Скриптом копировать из папок синхронизации в папку с программой не пойдет?

**Comment by bdi1979** [comment]
> Скриптом копировать из папок синхронизации в папку с программой не пойдет?
А как быть с базой оргтехники?
Которая всё равно будет синхронизирована с конторой, у которой не должно быть доступа к ней!
Вся проблема как раз в этом!
Желательно чтобы файл с базой не выходил за пределы, и не попадал куда не надо!

**Comment by bdi1979** [comment]
> Скриптом копировать из папок синхронизации в папку с программой не пойдет?

А как быть с базой оргтехники?
Которая всё равно будет синхронизирована с конторой, у которой не должно быть доступа к ней!
Вся проблема как раз в этом!
Желательно чтобы файл с базой не выходил за пределы, и не попадал куда не надо!

**Comment by bdi1979** [comment]
> > Скриптом копировать из папок синхронизации в папку с программой не пойдет?
> 
> А как быть с базой оргтехники?
> Которая всё равно будет синхронизирована с конторой, у которой не должно быть доступа к ней!
> Вся проблема как раз в этом!
> Желательно чтобы файл с базой не выходил за пределы, и не попадал куда не надо!

Как ни пытался ничего в голову не приходит как даже временное решение.

**Comment by ldragon24** [comment]
Но Вам никто не запрещает хранить основную базу в другой директории, а в папку с программой скидывать базы:

@ECHO OFF
SET sourcedir= d:\123
SET destdir= d:\321

for %%a in (%sourcedir%) do set CURRENT_DIR_NAME=%%~na

for %%c in (%sourcedir%\*.*) do (
  copy %%c %destdir%\%%~nc_%CURRENT_DIR_NAME%%%~xc
)
GOTO :EOF 

И таким образом у вас файлы баз будут иметь вид - имяфайла_имядиректорииизкоторойскопировали.mdb
