### ISSUE TITLE
Проблема с задвоением в отчёте

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#31]
Создал новую базу.
Сделал структуру компании.
Набрал несколько компьютеров МФУ и принтеров.

При формировании отчёта по компьютерам дублируются компьютеры в отчёте и выходят непонятные данные видимо остатки данных в базе от автора!
Скриншот во вложении!

**Comment by bdi1979** [comment]
![Ошибка с задвоением компьютеров в ПО БКО](https://user-images.githubusercontent.com/73057798/132718415-6161be20-59c0-4985-8ff9-fe6921e4e7c7.png)
Вот сам скрин с ошибкой и сама база во вложении!

**Comment by bdi1979** [comment]
![Ошибка с задвоением компьютеров в ПО БКО](https://user-images.githubusercontent.com/73057798/132719082-8611c072-c730-4fc6-b116-2743d8f1599a.png)
Вот более детальный скриншот с описанием что и как.

**Comment by bdi1979** [comment]
Есть ли возможность очистки базы вообще от всех данных кроме того что необходимо для начала работы с пустой базы?

**Comment by bdi1979** [comment]
> Создал новую базу.
> Сделал структуру компании.
> Набрал несколько компьютеров МФУ и принтеров.
> 
> При формировании отчёта по компьютерам дублируются компьютеры в отчёте и выходят непонятные данные видимо остатки данных в базе от автора!
> Скриншот во вложении!

Вот что еще хотел уточнить. Ввод компов делал вручную, только наименования и то что на первой закладке вволится из необходимого миниума!

**Comment by ldragon24** [comment]
1. Сервис\Обслуживание БД\Очистка
Очистит всю базу
2. В ближайшее время решу вопрос с задвоением.

**Comment by bdi1979** [comment]
> 1. Сервис\Обслуживание БД\Очистка
>    Очистит всю базу
> 2. Скачайте вот этот архив - https://drive.google.com/file/d/1x-AxvFpFNtQEZWPsu0b4c1hdNVPTJ-mz/view?usp=sharing

Я уже пробовал так, не помогло!
Старые данные остаются.

**Comment by bdi1979** [comment]
> 1. Сервис\Обслуживание БД\Очистка
>    Очистит всю базу
> 2. Скачайте вот этот архив - https://drive.google.com/file/d/1x-AxvFpFNtQEZWPsu0b4c1hdNVPTJ-mz/view?usp=sharing

После установки данного обновления задвоение данных в отчёте исчезло! Спасибо, за исправление.

**Comment by bdi1979** [comment]
> > 1. Сервис\Обслуживание БД\Очистка
> >    Очистит всю базу
> > 2. Скачайте вот этот архив - https://drive.google.com/file/d/1x-AxvFpFNtQEZWPsu0b4c1hdNVPTJ-mz/view?usp=sharing
> 
> Я уже пробовал так, не помогло!
> Старые данные остаются.

А вот эту проблему решили?

**Comment by ldragon24** [comment]
А Вы скачали обновление, заменили все файлы и попробовали очистить базу?

**Comment by bdi1979** [comment]
Спасибо за исправление!
