### ISSUE TITLE
Сброс пароля администратора

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#32]
Подскажите существует ли возможность сбросить забытый пароль Администратора ПО БКО?

**Comment by ldragon24** [comment]
Если удалить все данные из таблицы T_USER то программа при запуске восстановит админа по умолчанию

**Comment by bdi1979** [comment]
> Если удалить все данные из таблицы T_USER то программа при запуске восстановит админа по умолчанию

Подскажите пожалуйста, стандартный Логин и пароль?

**Comment by bdi1979** [comment]
> Если удалить все данные из таблицы T_USER то программа при запуске восстановит админа по умолчанию

Удалил все данные из таблицы T_USER
Запускаю программу БКО, ввожу логин ADMINISTRATOR и пароль admin и выходит ошибка: This User is not valid

**Comment by ldragon24** [comment]
ADMINISTRATOR/admin

**Comment by ldragon24** [comment]
https://drive.google.com/file/d/1x-AxvFpFNtQEZWPsu0b4c1hdNVPTJ-mz/view?usp=sharing

скачайте обновление, замените все файлы.

**Comment by bdi1979** [comment]
> https://drive.google.com/file/d/1x-AxvFpFNtQEZWPsu0b4c1hdNVPTJ-mz/view?usp=sharing
> 
> скачайте обновление, замените все файлы.

Это обновление уже стоит на данной системе!

**Comment by bdi1979** [comment]
Спасибо за исправление!
