### ISSUE TITLE
Поиск

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#33]
Вот ещё заметил какой баг.
В той же базе где и задвоение данных в отчёте вот какой глюк в поиске.
Поиском находит нужное количество объектов, но при попытке перейти на выбранный объект двойным кликом мыши перехода на объект не происходит!

**Comment by bdi1979** [comment]
ОС Windows 10 x64 RUS

**Comment by ldragon24** [comment]
Зависит от настроек отображения дерева техники. Зайдите в настройки программы и посмотрите какие параметры указаны.

**Comment by bdi1979** [comment]
> Зависит от настроек отображения дерева техники. Зайдите в настройки программы и посмотрите какие параметры указаны.

Вот скрин настроек:
![Скриншот настроек программы БКО](https://user-images.githubusercontent.com/73057798/134815341-bc16a4ca-3344-470b-9a5b-07c2b5c48fdd.png)

**Comment by ldragon24** [comment]
Статически обновляемое поставьте, и все будет как надо.

**Comment by bdi1979** [comment]
> Статически обновляемое поставьте, и все будет как надо.

Спасибо большое за подсказку!

**Comment by bdi1979** [comment]
Проблема решена
