### ISSUE TITLE
Проблема с Инвентарными номерами в программе и отчётах в версии 1.7.6.5

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#35]
После обновления до версии v1.7.6.5 при формировании отчётов по оргтехнике, в отчёт не выгружаются Инвентарные номера для всей оргтехники кроме компьютеров!

![Глюк в БКО в отчётах с инвентарными номерами](https://user-images.githubusercontent.com/73057798/135216345-35248c73-02f7-45af-846d-7442e5b779a7.png)

Проверил абсолютно на всех единицах. Инвентарные номера попадают в отчёт только по компьютерам!

**Comment by bdi1979** [comment]
В самой программе тоже Инвентарные номера у комплектующих не отображаются хотя в базе они есть!

**Comment by ldragon24** [comment]
пришлите базу, у меня все отображается.

**Comment by bdi1979** [comment]
Отправил базу на личную почту

**Comment by bdi1979** [comment]
С новым последним обновлением то же самое!

**Comment by bdi1979** [comment]
Спасибо за исправления и базу
