### ISSUE TITLE
Проблема со справочником оборудования

### ISSUE THREAD

**Issue by bdi1979** [ldragon24/bko#36]
При попытке добавить нового поставщика выходит вот какая ошибка:

![2021-10-01 - screenshot](https://user-images.githubusercontent.com/73057798/135603931-5d51f497-d85d-4182-a6d3-f4966367efde.png)

**Comment by ldragon24** [comment]
исправление - https://drive.google.com/file/d/1x-AxvFpFNtQEZWPsu0b4c1hdNVPTJ-mz/view?usp=sharing

**Comment by bdi1979** [comment]
> исправление - https://drive.google.com/file/d/1x-AxvFpFNtQEZWPsu0b4c1hdNVPTJ-mz/view?usp=sharing

Спасибо за исправление!
