### ISSUE TITLE
Раскрывающийся список "Отдел" не работает

### ISSUE THREAD

**Issue by bitewolf** [ldragon24/bko#37]
На последней версии 1.7.6.7 и предпоследней 1.7.6.6 не раскрывается список "Отдел", при чем только у единицы "Компьютер". У принтеров и ИБП - работает. Думал, что проблема с моей базой, но пробовал ставить чистую версию с дефолтной базой - результат тот же. Нашел установщик старой версии 1.7.6.3, там данной проблемы нет.

Пример проблемы:
![1767](https://user-images.githubusercontent.com/6371699/191266156-d3b1f560-06c6-4bed-a763-a7845e7483e1.png)

В старой версии все ок:
![1763](https://user-images.githubusercontent.com/6371699/191266164-2043cf5c-128f-4f41-9929-1fa19f5e3ab6.png)

**Comment by ldragon24** [comment]
https://github.com/ldragon24/bko/blob/master/_FILES/basainstall_17.exe

Исправлено

**Comment by bitewolf** [comment]
Спасибо, работает!
